service: simple

plugins:
  - ../..

provider:
  name: aws

custom:
  enhancedConfig:
    template: template.yml
    variables:
      service: simple
      function:
        name: myfunc
        handler: handlers/myfunc.main
        path: mypath/myfunc
        method: get
        cors: true
